[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *"

[build]
  publish = "_site"
  command = "npm run build"

[[edge_functions]]
  function = "facebook-bot"
  path = "/*"
